
CREATE TABLE IF NOT EXISTS USERS (
    USERNAME  VARCHAR(64) PRIMARY KEY,
    PASSWORD  VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    USERNAME  VARCHAR(64),
    ROLE_NAME  VARCHAR(64),
);

CREATE TABLE IF NOT EXISTS CHAT (
    CHAT_ID  VARCHAR(64) PRIMARY KEY,
    CHANNEL_ID  VARCHAR(64),
    CHANNEL_NAME  VARCHAR(64),
    CHANNEL_TYPE  VARCHAR(64),
);

CREATE TABLE IF NOT EXISTS MEMBERS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    GROUP_CHAT_ID  VARCHAR(64),
    USER_CHAT_ID  VARCHAR(64),
);
