
CREATE TABLE IF NOT EXISTS USERS (
    USERNAME  VARCHAR(64) PRIMARY KEY,
    PASSWORD  VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    USERNAME  VARCHAR(64),
    ROLE_NAME  VARCHAR(64),
)