
CREATE TABLE IF NOT EXISTS USERS (
    USERNAME  VARCHAR(64) PRIMARY KEY,
    PASSWORD  VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    USERNAME  VARCHAR(64),
    ROLE_NAME  VARCHAR(64),
);

CREATE TABLE IF NOT EXISTS PERSONAL_CHAT (
    USER_ID  VARCHAR(64) PRIMARY KEY,
    CHANNEL_ID  VARCHAR(64),
);

CREATE TABLE IF NOT EXISTS GROUP_CHAT (
    GROUP_ID VARCHAR(64) PRIMARY KEY,
    CHANNEL_ID  VARCHAR(64),
);

CREATE TABLE IF NOT EXISTS MEMBERS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    GROUP_ID  VARCHAR(64),
    USER_ID  VARCHAR(64),
);
